"""Added expires_at column

Revision ID: 09289b5e4dca
Revises: 3d3a67839851
Create Date: 2026-06-25 05:47:54.542904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09289b5e4dca'
down_revision: Union[str, Sequence[str], None] = '3d3a67839851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'expires_at')
    # ### end Alembic commands ###
